### ISSUE TITLE
ID Claim 073: Hazard Persistance Enjoyer

### ISSUE THREAD

**Issue by DarthPointer** [ArcticEcho/DRG-Mod-Loader#13]
Mod ID: 073
Mod Name: HazardPersistanceEnjoyer
Mod Author: Darth Pointer

**Comment by ArcticEcho** [comment]
Heya, just want to make sure you're aware of the changes in U34.5. Does this mod definitely need to use the manager for loading?

**Comment by DarthPointer** [comment]
Yes. For now vanilla fails to invoke the spawn for not-first rig scene load.
Despite devs claiming it only bugs for medbay, I just don't get a DRG Lib to spawn and spawn mods on any rig load after a mission.

**Comment by ArcticEcho** [comment]
Alright, no worries. Added.
