### ISSUE TITLE
ID Claim

### ISSUE THREAD

**Issue by Henri-J-Norden** [ArcticEcho/DRG-Mod-Loader#14]
Mod ID: 099
Mod Name: Message Of The Day
Mod Author: Glosb

MOTD / server welcome message mod!
Automatically posts a message in chat whenever a person joins your lobby. Special escape codes can be inserted in the message to be replaced with personalized values - currently (the joined person's) username, overall rank, ping and a count of how many times they have been in your lobby before. Feel free to leave suggestions/ideas what other values to add!

Other features:
* 10 save slots, so you can switch to a different welcome message for e.g. different play style modpacks or just have some messages to paste in chat with the manual "post message" button.
* The automatic message feature can be turned off by disabling the mod in the BPMM mod menu.

**Comment by ArcticEcho** [comment]
Added!
