### ISSUE TITLE
ID Claim 075: Text Commands Wheel

### ISSUE THREAD

**Issue by DarthPointer** [ArcticEcho/DRG-Mod-Loader#15]
Mod ID: 075 
Mod Name: Text Commands Wheel
Mod Author: Darth Pointer

That is it, I assume it is my last legacy-BPMM using mod.
Still not sure if I will transfer existing ones to new system any soon.

**Comment by ArcticEcho** [comment]
Added. 

There's no pressure to migrate your old mods to the native spawning system, it's totally up to you.
