### ISSUE TITLE
ID Claim

### ISSUE THREAD

**Issue by NaturalBornCamper** [ArcticEcho/DRG-Mod-Loader#17]
Mod ID: 100
Mod Name: Higher Difficulty Tweaks
Mod Author: NaturalBornCamper

Merges "cheaper ressuplies", "Doretta improved armor" and "Escort rocks reduced health" with an interface to adjust each value and reduce the clutter on mod.io, merging 7 mods into 1.

**Comment by ArcticEcho** [comment]
Added!
