### ISSUE TITLE
ID Claim

### ISSUE THREAD

**Issue by NaturalBornCamper** [ArcticEcho/DRG-Mod-Loader#18]
Mod ID: 101
Mod Name: Verified QoL Tweaks
Mod Author: NaturalBornCamper

Client-side, verified mods containing general QoL improvements that can be toggled/adjusted like disable Steeve petting, pipe repair radius, laser pointer tag duration, dash perk activation window, Custom perk key assignment, etc. Once again to reduce clutter and have a single mod to make adjustements instead of several variations of the same mod to enable/disable in game

**Comment by ArcticEcho** [comment]
Added!
