### ISSUE TITLE
ID Claim 102: Retrograde Mod Spawner

### ISSUE THREAD

**Issue by DarthPointer** [ArcticEcho/DRG-Mod-Loader#19]
Mod ID: 102
Mod Name: Retrograde Mod Spawner
Mod Author: Darth Pointer

A shell over BPMM mod spawning to spawn other mods without having to use manifested IDs and ID-named actors to use it. Can't really turn into a BPMM killer since it depends on it and getting mod spawned by this implies you have to add suport for each mod separately. Mostly designed for my personal modding workflow and mod bundling but 3rd party mods could use it too.

**Comment by ArcticEcho** [comment]
Added!
