### ISSUE TITLE
The request for more details of tutorial about blueprint modding

### ISSUE THREAD

**Issue by lufwa** [ArcticEcho/DRG-Mod-Loader#5]
Hi, I am a beginner of UE4 and I'd like blueprint modding which can trigger given talk when touch certain key. I found tutorial lacks too many details when starting blueprint modding. Therefore, would you mind providing more details or just several blueprint modding examples on the tutorial so I can fix my problematic blueprint modding? (It seems example given by Rauliken's tutorial has nothing with the tutorial:( )

**Comment by ArcticEcho** [comment]
Hey, I don't know which tutorial you're referring to. This repo only has a basic guide on how to use the mod loader. This isn't a tutorial on general BP modding.

**Comment by lufwa** [comment]
> Hey, I don't know which tutorial you're referring to. This repo only has a basic guide on how to use the mod loader. This isn't a tutorial on general BP modding.

All right :(
